Allow application to startup if "zeromq" dependency is missing.
Traceback (most recent call last):
  File "pmx.py", line 74, in <module>
    sys.exit(main(sys.argv))
  File "pmx.py", line 71, in main
    runPrymatexApplication(options, args)
  File "pmx.py", line 62, in runPrymatexApplication
    return pmx and pmx.exec_() or -1
  File "/Users/KelSolaar/Documents/Developement/ThirdParty/prymatex/prymatex/core/app.py", line 56, in exec_
    self.setupZeroMQContext()
  File "/Users/KelSolaar/Documents/Developement/ThirdParty/prymatex/prymatex/core/app.py", line 183, in setupZeroMQContext
    from prymatex.utils import zeromqt
  File "/Users/KelSolaar/Documents/Developement/ThirdParty/prymatex/prymatex/utils/zeromqt.py", line 1, in <module>
    import zmq
ImportError: No module named zmq